### ISSUE TITLE
Spark version is not same as in file docker-compose.yml

### ISSUE THREAD

**Issue by Aalnafessah** [Danny4927/docker-spark#1]
Hi 

I have install all the "docker-compose.yml" on the new version of docker swarm. I have lunch the spark-shell on the master but i got this 
<img width="1223" alt="screen shot 2017-10-29 at 12 53 13 pm" src="https://user-images.githubusercontent.com/30182419/32143867-3920be58-bca8-11e7-9cc3-234afd0794ad.png">

As you can see , its spark 2.0.2 not 2.2.0. 
Anyone know what is the problem ?

**Comment by Danny4927** [comment]
Hey @Aalnafessah, sorry this is an issue of the latest version. If you specify the version number it should work. I will fix this in a few seconds.
